# Generated by Django 6.0.3 on 2026-03-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200)),
                ("ip_address", models.GenericIPAddressField(unique=True)),
                ("mac_address", models.CharField(blank=True, max_length=20)),
                ("vendor", models.CharField(blank=True, max_length=200)),
                ("status", models.CharField(max_length=20)),
                ("last_check", models.DateTimeField()),
            ],
        ),
    ]
