# Generated by Django 6.0.3 on 2026-03-10 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitor", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="mac_address",
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
    ]
